version: '3.1'

services:
    php:
        build: .
        depends_on: 
            - mysql
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html/
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'student'
            MYSQL_PASSWORD: 'veiligwachtwoord'
        volumes:
            - mysqldata:/var/lib/mysql
            - certs:/ssl
            - mysqlconf:/etc/mysql/conf.d/
        ports:
            - 3306:3306

volumes:
    mysqldata:
    certs:
    mysqlconf:
